//for auth
export const USER_AUTHED = 'USER_AUTHED';

//for timer job
export const FETCHING_TIMER_JOBS = 'FETCHING_TIMER_JOBS';
export const FETCH_TIMER_JOBS_SUCCESS = 'FETCH_TIMER_JOBS_SUCCESS';
export const FETCH_TIMER_JOBS_FAIL = 'FETCH_TIMER_JOBS_FAIL';
export const TIMER_JOB_SELECTED = 'TIMER_JOB_SELECTED';

export const OPERATE_JOB = 'OPERATE_JOB';
export const OPEN_OPERATE_JOB_MODAL = 'OPEN_OPERATE_JOB_MODAL';
export const CLOSE_OPERATE_JOB_MODAL = "CLOSE_OPERATE_JOB_MODAL";

export const PROCESSING_JOB = 'PROCESSING_JOB'
export const PROCESSING_JOB_SUCCESS = 'PROCESSING_JOB_SUCCESS'
export const PROCESSING_JOB_FAIL = 'PROCESSING_JOB_FAIL'